# Before deploy this stack, run gradle :jibDockerBuild to build images

name: "roadeye"

services:
  api:
    image: roadeye/api:latest
    ports:
      - "8080:8080"
    env_file:
      - local.env
    depends_on:
      - mysql
      - rabbitmq
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      timeout: 10s
      retries: 5
      start_period: 10s
  hub:
    image: roadeye/hub:latest
    ports:
      - "8081:8080"
    env_file:
      - local.env
    depends_on:
      - mysql
      - rabbitmq
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      timeout: 10s
      retries: 5
      start_period: 10s
  consumer:
    image: roadeye/consumer:latest
    depends_on:
      - mysql
      - rabbitmq
    env_file:
      - local.env
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      timeout: 10s
      retries: 5
      start_period: 10s
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=roadeye
      - MYSQL_USER=roadeye
      - MYSQL_PASSWORD=roadeye
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 30s
      retries: 5
      start_period: 30s
  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=roadeye
      - RABBITMQ_DEFAULT_USER=roadeye
      - RABBITMQ_DEFAULT_PASS=roadeye
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
