spring:
  profiles:
    include: amqp
  datasource:
    hikari:
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1200
        order_inserts: true
        order_updates: true
  rabbitmq:
    listener:
      simple:
        prefetch: 100
        batch-size: 10
        concurrency: 5
        max-concurrency: 10
        default-requeue-rejected: false
        consumer-batch-enabled: false
        retry:
          enabled: true
      batch:
        prefetch: 30
        batch-size: 30
        consumers: 10
        maxConsumers: 10

