name: Deploy Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

concurrency:
  group: 'deploy-dev-docker'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Caching Gradle dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Caching Jib layers
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-jib-${{ hashFiles('**/build.gradle*', '**/settings.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-jib-
          path: |
            ~/.cache/google-cloud-tools-java/jib/images
            ~/.cache/google-cloud-tools-java/jib/layers

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Projects
        id: build
        run: |
          ./gradlew --quiet --build-cache \
            :roadeye-api:roadeye-api-hq:jibDockerBuild \
            :roadeye-api:roadeye-api-hub:jibDockerBuild \
            :roadeye-consumer:jibDockerBuild \
              -Djib.to.tags=latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to AWS
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push API-HQ image to ECR
        run: |
          docker tag roadeye-api-hq:latest ${{ secrets.AWS_ECR_REPOSITORY }}/roadeye/api-hq:latest
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}/roadeye/api-hq:latest

      - name: Push API-Hub image to ECR
        run: |
          docker tag roadeye-api-hub:latest ${{ secrets.AWS_ECR_REPOSITORY }}/roadeye/api-hub:latest
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}/roadeye/api-hub:latest

      - name: Push Consumer image to ECR
        run: |
          docker tag roadeye-consumer:latest ${{ secrets.AWS_ECR_REPOSITORY }}/roadeye/consumer:latest
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}/roadeye/consumer:latest
